//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceInventoryOpening {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceInventoryOpening() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceInventoryOpening", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Component.
        /// </summary>
        internal static string LblAircraftComponentId {
            get {
                return ResourceManager.GetString("LblAircraftComponentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Inventory Opening List.
        /// </summary>
        internal static string LblAllInventoryOpeningList {
            get {
                return ResourceManager.GetString("LblAllInventoryOpeningList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        internal static string LblApprovedBy {
            get {
                return ResourceManager.GetString("LblApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Inventory Opening List.
        /// </summary>
        internal static string LblApprovedInventoryOpeningList {
            get {
                return ResourceManager.GetString("LblApprovedInventoryOpeningList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved On.
        /// </summary>
        internal static string LblApprovedOn {
            get {
                return ResourceManager.GetString("LblApprovedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Remaining.
        /// </summary>
        internal static string LblCycleRemaining {
            get {
                return ResourceManager.GetString("LblCycleRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Since New.
        /// </summary>
        internal static string LblCycleSinceNew {
            get {
                return ResourceManager.GetString("LblCycleSinceNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string LblExpiryDate {
            get {
                return ResourceManager.GetString("LblExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRN No..
        /// </summary>
        internal static string LblGRNNumber {
            get {
                return ResourceManager.GetString("LblGRNNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Opening.
        /// </summary>
        internal static string LblInventoryOpening {
            get {
                return ResourceManager.GetString("LblInventoryOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string LblManufacturerId {
            get {
                return ResourceManager.GetString("LblManufacturerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model No.
        /// </summary>
        internal static string LblModelNo {
            get {
                return ResourceManager.GetString("LblModelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No inventory opening found.
        /// </summary>
        internal static string LblNoInventoryOpeningFound {
            get {
                return ResourceManager.GetString("LblNoInventoryOpeningFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open By.
        /// </summary>
        internal static string LblOpenBy {
            get {
                return ResourceManager.GetString("LblOpenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Date.
        /// </summary>
        internal static string LblOpeningDate {
            get {
                return ResourceManager.GetString("LblOpeningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Remarks.
        /// </summary>
        internal static string LblOtherRemarks {
            get {
                return ResourceManager.GetString("LblOtherRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part No..
        /// </summary>
        internal static string LblPartNo {
            get {
                return ResourceManager.GetString("LblPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval Inventory Opening List.
        /// </summary>
        internal static string LblPendingApprovalInventoryOpeningList {
            get {
                return ResourceManager.GetString("LblPendingApprovalInventoryOpeningList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared Inventory Opening List.
        /// </summary>
        internal static string LblPreparedInventoryOpeningList {
            get {
                return ResourceManager.GetString("LblPreparedInventoryOpeningList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty..
        /// </summary>
        internal static string LblQuantity {
            get {
                return ResourceManager.GetString("LblQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack Life Type.
        /// </summary>
        internal static string LblRackLifeType {
            get {
                return ResourceManager.GetString("LblRackLifeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin Code.
        /// </summary>
        internal static string LblRackRowBinId {
            get {
                return ResourceManager.GetString("LblRackRowBinId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No..
        /// </summary>
        internal static string LblSerialNo {
            get {
                return ResourceManager.GetString("LblSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spare Float Quantity.
        /// </summary>
        internal static string LblSpareFloatQty {
            get {
                return ResourceManager.GetString("LblSpareFloatQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Since New (Hours).
        /// </summary>
        internal static string LblTimeSinceNew {
            get {
                return ResourceManager.GetString("LblTimeSinceNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total inventory opening.
        /// </summary>
        internal static string LblTotalInventoryOpening {
            get {
                return ResourceManager.GetString("LblTotalInventoryOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measurement.
        /// </summary>
        internal static string LblUnitofMeasurement {
            get {
                return ResourceManager.GetString("LblUnitofMeasurement", resourceCulture);
            }
        }
    }
}
