//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceCommon", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved successfully!.
        /// </summary>
        internal static string CMsg_defaultSave {
            get {
                return ResourceManager.GetString("CMsg_defaultSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted successfully !.
        /// </summary>
        internal static string CMsg_delete {
            get {
                return ResourceManager.GetString("CMsg_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save. Same {0} name found!.
        /// </summary>
        internal static string CMsg_duplicate {
            get {
                return ResourceManager.GetString("CMsg_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be deleted !.
        /// </summary>
        internal static string CMsg_notdelete {
            get {
                return ResourceManager.GetString("CMsg_notdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be updated !.
        /// </summary>
        internal static string CMsg_notupdate {
            get {
                return ResourceManager.GetString("CMsg_notupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station and Dependent Station must be different..
        /// </summary>
        internal static string CMsg_sameError {
            get {
                return ResourceManager.GetString("CMsg_sameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saved successfully !.
        /// </summary>
        internal static string CMsg_save {
            get {
                return ResourceManager.GetString("CMsg_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved All.
        /// </summary>
        internal static string CMsg_saveall {
            get {
                return ResourceManager.GetString("CMsg_saveall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be saved !.
        /// </summary>
        internal static string CMsg_unsave {
            get {
                return ResourceManager.GetString("CMsg_unsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated successfully !.
        /// </summary>
        internal static string CMsg_update {
            get {
                return ResourceManager.GetString("CMsg_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Save.
        /// </summary>
        internal static string FileRead {
            get {
                return ResourceManager.GetString("FileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string LblAction {
            get {
                return ResourceManager.GetString("LblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add+.
        /// </summary>
        internal static string LblAddDetailItem {
            get {
                return ResourceManager.GetString("LblAddDetailItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add+.
        /// </summary>
        internal static string LblAddPlus {
            get {
                return ResourceManager.GetString("LblAddPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string LblApprove {
            get {
                return ResourceManager.GetString("LblApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve/Reject.
        /// </summary>
        internal static string LblApproveOrReject {
            get {
                return ResourceManager.GetString("LblApproveOrReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string LblChange {
            get {
                return ResourceManager.GetString("LblChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string LblCreateNew {
            get {
                return ResourceManager.GetString("LblCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string LblDelete {
            get {
                return ResourceManager.GetString("LblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string LblDetail {
            get {
                return ResourceManager.GetString("LblDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string LblEdit {
            get {
                return ResourceManager.GetString("LblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered.
        /// </summary>
        internal static string lblFiltered {
            get {
                return ResourceManager.GetString("lblFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string LblFirst {
            get {
                return ResourceManager.GetString("LblFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string LblFromDate {
            get {
                return ResourceManager.GetString("LblFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string LblHide {
            get {
                return ResourceManager.GetString("LblHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string LblIsActive {
            get {
                return ResourceManager.GetString("LblIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Item.
        /// </summary>
        internal static string LblIssueItem {
            get {
                return ResourceManager.GetString("LblIssueItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string LblLast {
            get {
                return ResourceManager.GetString("LblLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string lblList {
            get {
                return ResourceManager.GetString("lblList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string LblNext {
            get {
                return ResourceManager.GetString("LblNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        internal static string lblPageSize {
            get {
                return ResourceManager.GetString("lblPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending List.
        /// </summary>
        internal static string LblPendingList {
            get {
                return ResourceManager.GetString("LblPendingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare.
        /// </summary>
        internal static string LblPrepare {
            get {
                return ResourceManager.GetString("LblPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string LblPrevious {
            get {
                return ResourceManager.GetString("LblPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Out.
        /// </summary>
        internal static string LblPrintOut {
            get {
                return ResourceManager.GetString("LblPrintOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive/Reject.
        /// </summary>
        internal static string LblReceiveOrReject {
            get {
                return ResourceManager.GetString("LblReceiveOrReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string LblRemove {
            get {
                return ResourceManager.GetString("LblRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string LblReport {
            get {
                return ResourceManager.GetString("LblReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string LblReset {
            get {
                return ResourceManager.GetString("LblReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string LblReview {
            get {
                return ResourceManager.GetString("LblReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed List.
        /// </summary>
        internal static string LblReviewedList {
            get {
                return ResourceManager.GetString("LblReviewedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string LblSearch {
            get {
                return ResourceManager.GetString("LblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string LblSelect {
            get {
                return ResourceManager.GetString("LblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string LblShow {
            get {
                return ResourceManager.GetString("LblShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Unrecived.
        /// </summary>
        internal static string LblShowAllUnreceived {
            get {
                return ResourceManager.GetString("LblShowAllUnreceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string LblSubmit {
            get {
                return ResourceManager.GetString("LblSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string LblView {
            get {
                return ResourceManager.GetString("LblView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        internal static string LblViewAll {
            get {
                return ResourceManager.GetString("LblViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose a file..
        /// </summary>
        internal static string MgsChooseAFile {
            get {
                return ResourceManager.GetString("MgsChooseAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error in uploading file on server!.
        /// </summary>
        internal static string MgsErrorInUploadingFile {
            get {
                return ResourceManager.GetString("MgsErrorInUploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission to create.
        /// </summary>
        internal static string MgsNoPermissionToCreate {
            get {
                return ResourceManager.GetString("MgsNoPermissionToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission to delete.
        /// </summary>
        internal static string MgsNoPermissionToDelete {
            get {
                return ResourceManager.GetString("MgsNoPermissionToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission to read.
        /// </summary>
        internal static string MgsNoPermissionToRead {
            get {
                return ResourceManager.GetString("MgsNoPermissionToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission to update.
        /// </summary>
        internal static string MgsNoPermissionToUpdate {
            get {
                return ResourceManager.GetString("MgsNoPermissionToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide {0}.
        /// </summary>
        internal static string MgsProvideDetails {
            get {
                return ResourceManager.GetString("MgsProvideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from the details?.
        /// </summary>
        internal static string MsgConfirmRemoveFromTheDetails {
            get {
                return ResourceManager.GetString("MsgConfirmRemoveFromTheDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        internal static string MsgConfirm_Delete {
            get {
                return ResourceManager.GetString("MsgConfirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleted successfully!.
        /// </summary>
        internal static string MsgDeleted {
            get {
                return ResourceManager.GetString("MsgDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured in data loading.
        /// </summary>
        internal static string MsgErrorInLoading {
            get {
                return ResourceManager.GetString("MsgErrorInLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in saving data.
        /// </summary>
        internal static string MsgErrorInSaving {
            get {
                return ResourceManager.GetString("MsgErrorInSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string MsgHeaderSuccess {
            get {
                return ResourceManager.GetString("MsgHeaderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t be deleted!.
        /// </summary>
        internal static string MsgNot_deleted {
            get {
                return ResourceManager.GetString("MsgNot_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not saved..
        /// </summary>
        internal static string MsgNot_Saved {
            get {
                return ResourceManager.GetString("MsgNot_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not updated!.
        /// </summary>
        internal static string MsgNot_Updated {
            get {
                return ResourceManager.GetString("MsgNot_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved successfully..
        /// </summary>
        internal static string MsgSaved {
            get {
                return ResourceManager.GetString("MsgSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated successfully..
        /// </summary>
        internal static string MsgUpdated {
            get {
                return ResourceManager.GetString("MsgUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search text here.
        /// </summary>
        internal static string TextBoxSearch_Watermark {
            get {
                return ResourceManager.GetString("TextBoxSearch_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        internal static string VMsgRequired_Name {
            get {
                return ResourceManager.GetString("VMsgRequired_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Large.
        /// </summary>
        internal static string VMsgToo_Large {
            get {
                return ResourceManager.GetString("VMsgToo_Large", resourceCulture);
            }
        }
    }
}
