//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceReportConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceReportConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceReportConfiguration", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Folder.
        /// </summary>
        internal static string LblDestinationFolder {
            get {
                return ResourceManager.GetString("LblDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading Title.
        /// </summary>
        internal static string LblHeadingTitle {
            get {
                return ResourceManager.GetString("LblHeadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No report configuration found.
        /// </summary>
        internal static string LblNoReportConfigurationFound {
            get {
                return ResourceManager.GetString("LblNoReportConfigurationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File Extension.
        /// </summary>
        internal static string LblOutputFileExtension {
            get {
                return ResourceManager.GetString("LblOutputFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Configuration Details.
        /// </summary>
        internal static string LblReportConfDetails {
            get {
                return ResourceManager.GetString("LblReportConfDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Configuration.
        /// </summary>
        internal static string LblReportConfiguration {
            get {
                return ResourceManager.GetString("LblReportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roport Column Name.
        /// </summary>
        internal static string LblRoportColumnName {
            get {
                return ResourceManager.GetString("LblRoportColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Column Name.
        /// </summary>
        internal static string LblTableColumnName {
            get {
                return ResourceManager.GetString("LblTableColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total report configuration.
        /// </summary>
        internal static string LblTotalReportConfiguration {
            get {
                return ResourceManager.GetString("LblTotalReportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t generate report for the list..
        /// </summary>
        internal static string MgsCantGenerateReport {
            get {
                return ResourceManager.GetString("MgsCantGenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t generate report. Please, check &apos;OutputFileExtension&apos; in report configuration..
        /// </summary>
        internal static string MgsCheckFileExt {
            get {
                return ResourceManager.GetString("MgsCheckFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report can&apos;t save. The directory to the path &apos;{0}&apos; not exist as the report configuration..
        /// </summary>
        internal static string MgsDircetoryNotFound {
            get {
                return ResourceManager.GetString("MgsDircetoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEL could not be started. Check that your office installation and project references are correct..
        /// </summary>
        internal static string MgsExcelCouldNotStart {
            get {
                return ResourceManager.GetString("MgsExcelCouldNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List contains no rocords to generate report..
        /// </summary>
        internal static string MgsListEmpty {
            get {
                return ResourceManager.GetString("MgsListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No report configuration found for the name {} .
        /// </summary>
        internal static string MgsNoReportConfFound {
            get {
                return ResourceManager.GetString("MgsNoReportConfFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report configuration detail not found for &apos;{0}&apos;. .
        /// </summary>
        internal static string MgsReportConfDetailNotFoundInDb {
            get {
                return ResourceManager.GetString("MgsReportConfDetailNotFoundInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated to the path: {0}.{1}.
        /// </summary>
        internal static string MgsReportGeneratedToThePath {
            get {
                return ResourceManager.GetString("MgsReportGeneratedToThePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet could not be created. Check that your office installation and project references are correct..
        /// </summary>
        internal static string MgsWorksheetCouldNotCreate {
            get {
                return ResourceManager.GetString("MgsWorksheetCouldNotCreate", resourceCulture);
            }
        }
    }
}
