//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceUnserviceableItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUnserviceableItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceUnserviceableItem", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft.
        /// </summary>
        internal static string AirOverView {
            get {
                return ResourceManager.GetString("AirOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Part No.
        /// </summary>
        internal static string InsPartNo {
            get {
                return ResourceManager.GetString("InsPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Serial No.
        /// </summary>
        internal static string InsSerNo {
            get {
                return ResourceManager.GetString("InsSerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Issue.
        /// </summary>
        internal static string ItmIsu {
            get {
                return ResourceManager.GetString("ItmIsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Purchase Order.
        /// </summary>
        internal static string LblCrtPO {
            get {
                return ResourceManager.GetString("LblCrtPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Procurement Requisition.
        /// </summary>
        internal static string LblCrtProcReqr {
            get {
                return ResourceManager.GetString("LblCrtProcReqr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnserviceableItem deleted successfully!.
        /// </summary>
        internal static string LblDeleteUnserviceItem {
            get {
                return ResourceManager.GetString("LblDeleteUnserviceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        internal static string LblExchange {
            get {
                return ResourceManager.GetString("LblExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unserviceable Exchange Item List.
        /// </summary>
        internal static string LblExchangeitemList {
            get {
                return ResourceManager.GetString("LblExchangeitemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unserviceable Item List.
        /// </summary>
        internal static string LblListTitle {
            get {
                return ResourceManager.GetString("LblListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnserviceableItem can&apos;t be deleted!.
        /// </summary>
        internal static string LblNotDeleteUnserviceItem {
            get {
                return ResourceManager.GetString("LblNotDeleteUnserviceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unserviceable Item could not saved!.
        /// </summary>
        internal static string LblNotSaveUnseviceItem {
            get {
                return ResourceManager.GetString("LblNotSaveUnseviceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnserviceableItem could not updated!.
        /// </summary>
        internal static string LblNotUpdateUnseviceItem {
            get {
                return ResourceManager.GetString("LblNotUpdateUnseviceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unserviceable Item saved successfully!.
        /// </summary>
        internal static string LblSaveUnseviceItem {
            get {
                return ResourceManager.GetString("LblSaveUnseviceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicing.
        /// </summary>
        internal static string LblService {
            get {
                return ResourceManager.GetString("LblService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unserviceable Item.
        /// </summary>
        internal static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnserviceableItem updated successfully!.
        /// </summary>
        internal static string LblUpdateUnseviceItem {
            get {
                return ResourceManager.GetString("LblUpdateUnseviceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrenty Claim.
        /// </summary>
        internal static string LblWarrenty {
            get {
                return ResourceManager.GetString("LblWarrenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Exchange Unserviceable Item are found.
        /// </summary>
        internal static string NoExchangeFound {
            get {
                return ResourceManager.GetString("NoExchangeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No UnserviceableItem Found.
        /// </summary>
        internal static string NoitemFound {
            get {
                return ResourceManager.GetString("NoitemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Date.
        /// </summary>
        internal static string RemDate {
            get {
                return ResourceManager.GetString("RemDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Part No.
        /// </summary>
        internal static string RemPartNo {
            get {
                return ResourceManager.GetString("RemPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal Reason.
        /// </summary>
        internal static string RemReason {
            get {
                return ResourceManager.GetString("RemReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Serial No.
        /// </summary>
        internal static string RemSerialNo {
            get {
                return ResourceManager.GetString("RemSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Overview Required.
        /// </summary>
        internal static string ReqAirOverView {
            get {
                return ResourceManager.GetString("ReqAirOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Part Number Required.
        /// </summary>
        internal static string ReqInsPartNo {
            get {
                return ResourceManager.GetString("ReqInsPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Serial Number Required.
        /// </summary>
        internal static string ReqInsSerNo {
            get {
                return ResourceManager.GetString("ReqInsSerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Issue  Required.
        /// </summary>
        internal static string ReqItmIsu {
            get {
                return ResourceManager.GetString("ReqItmIsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Date Required.
        /// </summary>
        internal static string ReqRemDate {
            get {
                return ResourceManager.GetString("ReqRemDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Part Number Required.
        /// </summary>
        internal static string ReqRemPartNo {
            get {
                return ResourceManager.GetString("ReqRemPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Serial Number Required.
        /// </summary>
        internal static string ReqRemSerialNo {
            get {
                return ResourceManager.GetString("ReqRemSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unserviceable Servicing Item List.
        /// </summary>
        internal static string ServicingList {
            get {
                return ResourceManager.GetString("ServicingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        internal static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total Unserviceable Item List.
        /// </summary>
        internal static string TotalList {
            get {
                return ResourceManager.GetString("TotalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unserviceable Warrenty Claim Item List.
        /// </summary>
        internal static string WArClaimList {
            get {
                return ResourceManager.GetString("WArClaimList", resourceCulture);
            }
        }
    }
}
