//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceItemIssue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceItemIssue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceItemIssue", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Issue List.
        /// </summary>
        internal static string LblApprovedItemIssueList {
            get {
                return ResourceManager.GetString("LblApprovedItemIssueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Line No..
        /// </summary>
        internal static string LblCardLineNo {
            get {
                return ResourceManager.GetString("LblCardLineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        internal static string LblComponentId {
            get {
                return ResourceManager.GetString("LblComponentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand No..
        /// </summary>
        internal static string LblDemandNo {
            get {
                return ResourceManager.GetString("LblDemandNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Approved By.
        /// </summary>
        internal static string LblIssueApprovedBy {
            get {
                return ResourceManager.GetString("LblIssueApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Approved On.
        /// </summary>
        internal static string LblIssueApprovedOn {
            get {
                return ResourceManager.GetString("LblIssueApprovedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Issue List.
        /// </summary>
        internal static string LblIssuedIssueList {
            get {
                return ResourceManager.GetString("LblIssuedIssueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Voucher No..
        /// </summary>
        internal static string LblIssueVoucherNo {
            get {
                return ResourceManager.GetString("LblIssueVoucherNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Date.
        /// </summary>
        internal static string LblIssuingDate {
            get {
                return ResourceManager.GetString("LblIssuingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Store Keeper.
        /// </summary>
        internal static string LblIssuingStoreKeeper {
            get {
                return ResourceManager.GetString("LblIssuingStoreKeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Issue.
        /// </summary>
        internal static string LblItemIssue {
            get {
                return ResourceManager.GetString("LblItemIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Issue Details.
        /// </summary>
        internal static string LblItemIssueDetails {
            get {
                return ResourceManager.GetString("LblItemIssueDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Received By.
        /// </summary>
        internal static string LblMaterialReceivedBy {
            get {
                return ResourceManager.GetString("LblMaterialReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Receive On.
        /// </summary>
        internal static string LblMaterialReceiveOn {
            get {
                return ResourceManager.GetString("LblMaterialReceiveOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item issue found.
        /// </summary>
        internal static string LblNoItemIssueFound {
            get {
                return ResourceManager.GetString("LblNoItemIssueFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part No..
        /// </summary>
        internal static string LblPartNo {
            get {
                return ResourceManager.GetString("LblPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Issue List.
        /// </summary>
        internal static string LblPendingItemIssueList {
            get {
                return ResourceManager.GetString("LblPendingItemIssueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Balance.
        /// </summary>
        internal static string LblPresentStock {
            get {
                return ResourceManager.GetString("LblPresentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty. Issued.
        /// </summary>
        internal static string LblQuantityIssued {
            get {
                return ResourceManager.GetString("LblQuantityIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty. Remaining.
        /// </summary>
        internal static string LblQuantityRemaining {
            get {
                return ResourceManager.GetString("LblQuantityRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty. Required.
        /// </summary>
        internal static string LblQuantityRequired {
            get {
                return ResourceManager.GetString("LblQuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack Row Bin.
        /// </summary>
        internal static string LblRackRowBinId {
            get {
                return ResourceManager.GetString("LblRackRowBinId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string LblRemarks {
            get {
                return ResourceManager.GetString("LblRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total item issue.
        /// </summary>
        internal static string LblTotalItemIssue {
            get {
                return ResourceManager.GetString("LblTotalItemIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measurement.
        /// </summary>
        internal static string LblUnitOfMeasurement {
            get {
                return ResourceManager.GetString("LblUnitOfMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty. Exceeded..
        /// </summary>
        internal static string MgsQtyIssuedExceeded {
            get {
                return ResourceManager.GetString("MgsQtyIssuedExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty. Exceeded. Please, change the &apos;Quantity Issued&apos; field in grid..
        /// </summary>
        internal static string MgsQtyIssuedExceededChangePls {
            get {
                return ResourceManager.GetString("MgsQtyIssuedExceededChangePls", resourceCulture);
            }
        }
    }
}
