//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceItemDemand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceItemDemand() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceItemDemand", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Regn..
        /// </summary>
        internal static string LblACRegn {
            get {
                return ResourceManager.GetString("LblACRegn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Demand List.
        /// </summary>
        internal static string LblAllItemDemandList {
            get {
                return ResourceManager.GetString("LblAllItemDemandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        internal static string LblApprovedBy {
            get {
                return ResourceManager.GetString("LblApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved On.
        /// </summary>
        internal static string LblApprovedOn {
            get {
                return ResourceManager.GetString("LblApprovedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand For.
        /// </summary>
        internal static string LblDemandFor {
            get {
                return ResourceManager.GetString("LblDemandFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand No..
        /// </summary>
        internal static string LblDemandNo {
            get {
                return ResourceManager.GetString("LblDemandNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand On.
        /// </summary>
        internal static string LblDemandOn {
            get {
                return ResourceManager.GetString("LblDemandOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        internal static string LblDepartmentCode {
            get {
                return ResourceManager.GetString("LblDepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Demand.
        /// </summary>
        internal static string LblItemDemand {
            get {
                return ResourceManager.GetString("LblItemDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Demand Detail.
        /// </summary>
        internal static string LblItemDemandDetail {
            get {
                return ResourceManager.GetString("LblItemDemandDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Code.
        /// </summary>
        internal static string LblLocationCode {
            get {
                return ResourceManager.GetString("LblLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internal demand found.
        /// </summary>
        internal static string LblNoItemDemandFound {
            get {
                return ResourceManager.GetString("LblNoItemDemandFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part No..
        /// </summary>
        internal static string LblPartNo {
            get {
                return ResourceManager.GetString("LblPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Internal Demand List.
        /// </summary>
        internal static string LblPendingItemDemandList {
            get {
                return ResourceManager.GetString("LblPendingItemDemandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string LblPriority {
            get {
                return ResourceManager.GetString("LblPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty. Required.
        /// </summary>
        internal static string LblQuantityRequired {
            get {
                return ResourceManager.GetString("LblQuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested By.
        /// </summary>
        internal static string LblRequestedBy {
            get {
                return ResourceManager.GetString("LblRequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total internal demand.
        /// </summary>
        internal static string LblTotalItemDemand {
            get {
                return ResourceManager.GetString("LblTotalItemDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UoM.
        /// </summary>
        internal static string LblUnitOfMeasurement {
            get {
                return ResourceManager.GetString("LblUnitOfMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order No..
        /// </summary>
        internal static string LblWorkOrderNo {
            get {
                return ResourceManager.GetString("LblWorkOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Demand Detail not found..
        /// </summary>
        internal static string MgsItemDemandDetailNotFound {
            get {
                return ResourceManager.GetString("MgsItemDemandDetailNotFound", resourceCulture);
            }
        }
    }
}
