//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEmail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEmail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceEmail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative Statement has been rejected.
        /// </summary>
        internal static string CS_APPROVEDREJECT_SUBJECT {
            get {
                return ResourceManager.GetString("CS_APPROVEDREJECT_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative Statement has been approved.
        /// </summary>
        internal static string CS_APPROVED_SUBJECT {
            get {
                return ResourceManager.GetString("CS_APPROVED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative Statement has been prepared.
        /// </summary>
        internal static string CS_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("CS_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative Statement has been reviewed.
        /// </summary>
        internal static string CS_REVIEWED_SUBJECT {
            get {
                return ResourceManager.GetString("CS_REVIEWED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative Statement has been review.
        /// </summary>
        internal static string CS_REVIEWREJECT_SUBJECT {
            get {
                return ResourceManager.GetString("CS_REVIEWREJECT_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative Statement has been prepared again.
        /// </summary>
        internal static string CS_RE_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("CS_RE_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The demand No. {0}  has been approved. \n.
        /// </summary>
        internal static string DEMAND_APPROVE_BODY_1 {
            get {
                return ResourceManager.GetString("DEMAND_APPROVE_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demand approved by {0}.
        /// </summary>
        internal static string DEMAND_APPROVE_BODY_2 {
            get {
                return ResourceManager.GetString("DEMAND_APPROVE_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand has been approved!.
        /// </summary>
        internal static string DEMAND_APPROVE_SUBJECT {
            get {
                return ResourceManager.GetString("DEMAND_APPROVE_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New demand has been created with Demand No. {0}. \n.
        /// </summary>
        internal static string DEMAND_PENDING_BODY_1 {
            get {
                return ResourceManager.GetString("DEMAND_PENDING_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demand is waiting for your approval..
        /// </summary>
        internal static string DEMAND_PENDING_BODY_2 {
            get {
                return ResourceManager.GetString("DEMAND_PENDING_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Demand has been created!.
        /// </summary>
        internal static string DEMAND_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("DEMAND_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The demand No.{0}  has been rejected. \n.
        /// </summary>
        internal static string DEMAND_REJECT_BODY_1 {
            get {
                return ResourceManager.GetString("DEMAND_REJECT_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demand rejected by {0}.
        /// </summary>
        internal static string DEMAND_REJECT_BODY_2 {
            get {
                return ResourceManager.GetString("DEMAND_REJECT_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand has been rejected!.
        /// </summary>
        internal static string DEMAND_REJECT_SUBJECT {
            get {
                return ResourceManager.GetString("DEMAND_REJECT_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The demand has been updated with Demand No. {0}. \n.
        /// </summary>
        internal static string DEMAND_RE_PENDING_BODY_1 {
            get {
                return ResourceManager.GetString("DEMAND_RE_PENDING_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demand is waiting for your approval..
        /// </summary>
        internal static string DEMAND_RE_PENDING_BODY_2 {
            get {
                return ResourceManager.GetString("DEMAND_RE_PENDING_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Demand has been emeded!.
        /// </summary>
        internal static string DEMAND_RE_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("DEMAND_RE_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item issue has been approve rejected.
        /// </summary>
        internal static string ISSUE_APPROVEDREJECTED_SUBJECT {
            get {
                return ResourceManager.GetString("ISSUE_APPROVEDREJECTED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item issue has been approve.
        /// </summary>
        internal static string ISSUE_APPROVED_SUBJECT {
            get {
                return ResourceManager.GetString("ISSUE_APPROVED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item issue has been issued.
        /// </summary>
        internal static string ISSUE_ISSUED_SUBJECT {
            get {
                return ResourceManager.GetString("ISSUE_ISSUED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item issue has been prepared.
        /// </summary>
        internal static string ISSUE_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("ISSUE_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued item has been rejected.
        /// </summary>
        internal static string ISSUE_RECIEVEDREJECTED_SUBJECT {
            get {
                return ResourceManager.GetString("ISSUE_RECIEVEDREJECTED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued item has been accepted.
        /// </summary>
        internal static string ISSUE_RECIEVED_SUBJECT {
            get {
                return ResourceManager.GetString("ISSUE_RECIEVED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item issue has been prepared again.
        /// </summary>
        internal static string ISSUE_RE_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("ISSUE_RE_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item open request has been approved. \n.
        /// </summary>
        internal static string OPENING_APPROVED_BODY_1 {
            get {
                return ResourceManager.GetString("OPENING_APPROVED_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item open request was initiated by {0} on {1}.\n.
        /// </summary>
        internal static string OPENING_APPROVED_BODY_2 {
            get {
                return ResourceManager.GetString("OPENING_APPROVED_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is approved by {0}. \n.
        /// </summary>
        internal static string OPENING_APPROVED_BODY_3 {
            get {
                return ResourceManager.GetString("OPENING_APPROVED_BODY_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item opening has been approved!.
        /// </summary>
        internal static string OPENING_APPROVED_SUBJECT {
            get {
                return ResourceManager.GetString("OPENING_APPROVED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item open request has been rejected. \n.
        /// </summary>
        internal static string OPENING_APPROVEREJECTED_BODY_1 {
            get {
                return ResourceManager.GetString("OPENING_APPROVEREJECTED_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item open request was initiated by {0} on {1}. \n.
        /// </summary>
        internal static string OPENING_APPROVEREJECTED_BODY_2 {
            get {
                return ResourceManager.GetString("OPENING_APPROVEREJECTED_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is rejected by {0}. \n.
        /// </summary>
        internal static string OPENING_APPROVEREJECTED_BODY_3 {
            get {
                return ResourceManager.GetString("OPENING_APPROVEREJECTED_BODY_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item opening has been rejected!.
        /// </summary>
        internal static string OPENING_APPROVEREJECTED_SUBJECT {
            get {
                return ResourceManager.GetString("OPENING_APPROVEREJECTED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item opening has been initiated by {0} on {1}.\n.
        /// </summary>
        internal static string OPENING_PENDING_BODY_1 {
            get {
                return ResourceManager.GetString("OPENING_PENDING_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This requires your approval.\n.
        /// </summary>
        internal static string OPENING_PENDING_BODY_2 {
            get {
                return ResourceManager.GetString("OPENING_PENDING_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item opening!.
        /// </summary>
        internal static string OPENING_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("OPENING_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item opening has been updated by {0} on {1}. \n.
        /// </summary>
        internal static string OPENING_RE_PENDING_BODY_1 {
            get {
                return ResourceManager.GetString("OPENING_RE_PENDING_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This requires your approval.\n.
        /// </summary>
        internal static string OPENING_RE_PENDING_BODY_2 {
            get {
                return ResourceManager.GetString("OPENING_RE_PENDING_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item opening updated!.
        /// </summary>
        internal static string OPENING_RE_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("OPENING_RE_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Requisition has been rejected.
        /// </summary>
        internal static string PROCREQ_APPROVEDREJECT_SUBJECT {
            get {
                return ResourceManager.GetString("PROCREQ_APPROVEDREJECT_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Requisition has been approved.
        /// </summary>
        internal static string PROCREQ_APPROVED_SUBJECT {
            get {
                return ResourceManager.GetString("PROCREQ_APPROVED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Requisition has been prepared.
        /// </summary>
        internal static string PROCREQ_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("PROCREQ_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Requisition has been reviewed.
        /// </summary>
        internal static string PROCREQ_REVIEWED_SUBJECT {
            get {
                return ResourceManager.GetString("PROCREQ_REVIEWED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Requisition has been reviewed.
        /// </summary>
        internal static string PROCREQ_REVIEWREJECT_SUBJECT {
            get {
                return ResourceManager.GetString("PROCREQ_REVIEWREJECT_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Requisition has been prepared again.
        /// </summary>
        internal static string PROCREQ_RE_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("PROCREQ_RE_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Ordern has been rejected.
        /// </summary>
        internal static string PURORDER_APPROVEDREJECT_SUBJECT {
            get {
                return ResourceManager.GetString("PURORDER_APPROVEDREJECT_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order has been approved.
        /// </summary>
        internal static string PURORDER_APPROVED_SUBJECT {
            get {
                return ResourceManager.GetString("PURORDER_APPROVED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order has been prepared.
        /// </summary>
        internal static string PURORDER_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("PURORDER_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order has been reviewed.
        /// </summary>
        internal static string PURORDER_REVIEWED_SUBJECT {
            get {
                return ResourceManager.GetString("PURORDER_REVIEWED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order has been reviewed.
        /// </summary>
        internal static string PURORDER_REVIEWREJECT_SUBJECT {
            get {
                return ResourceManager.GetString("PURORDER_REVIEWREJECT_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order has been prepared again.
        /// </summary>
        internal static string PURORDER_RE_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("PURORDER_RE_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Scrap or Expire item request has been approved. \n.
        /// </summary>
        internal static string SCRAP_APPROVED_BODY_1 {
            get {
                return ResourceManager.GetString("SCRAP_APPROVED_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Scrap or Expire item(s) was initiated by {0} on {1}. \n.
        /// </summary>
        internal static string SCRAP_APPROVED_BODY_2 {
            get {
                return ResourceManager.GetString("SCRAP_APPROVED_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is approved by {0}. \n.
        /// </summary>
        internal static string SCRAP_APPROVED_BODY_3 {
            get {
                return ResourceManager.GetString("SCRAP_APPROVED_BODY_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap or Expire item has been approved!.
        /// </summary>
        internal static string SCRAP_APPROVED_SUBJECT {
            get {
                return ResourceManager.GetString("SCRAP_APPROVED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Scrap or Expire item request has been rejected. \n.
        /// </summary>
        internal static string SCRAP_APPROVEREJECTED_BODY_1 {
            get {
                return ResourceManager.GetString("SCRAP_APPROVEREJECTED_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Scrap or Expire item(s) was initiated by {0} on {1}. \n.
        /// </summary>
        internal static string SCRAP_APPROVEREJECTED_BODY_2 {
            get {
                return ResourceManager.GetString("SCRAP_APPROVEREJECTED_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is rejected by {0}. \n.
        /// </summary>
        internal static string SCRAP_APPROVEREJECTED_BODY_3 {
            get {
                return ResourceManager.GetString("SCRAP_APPROVEREJECTED_BODY_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap or Expire item has been rejected!.
        /// </summary>
        internal static string SCRAP_APPROVEREJECTED_SUBJECT {
            get {
                return ResourceManager.GetString("SCRAP_APPROVEREJECTED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap or Expire item(s) has been initiated by {0} on {1}. \n.
        /// </summary>
        internal static string SCRAP_PENDING_BODY_1 {
            get {
                return ResourceManager.GetString("SCRAP_PENDING_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This requires your approval. \n.
        /// </summary>
        internal static string SCRAP_PENDING_BODY_2 {
            get {
                return ResourceManager.GetString("SCRAP_PENDING_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap or Expire item!.
        /// </summary>
        internal static string SCRAP_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("SCRAP_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap or Expire item(s) has been updated by {0} on {1}. \n.
        /// </summary>
        internal static string SCRAP_RE_PENDING_BODY_1 {
            get {
                return ResourceManager.GetString("SCRAP_RE_PENDING_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This requires your approval. \n.
        /// </summary>
        internal static string SCRAP_RE_PENDING_BODY_2 {
            get {
                return ResourceManager.GetString("SCRAP_RE_PENDING_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap or Expire item!.
        /// </summary>
        internal static string SCRAP_RE_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("SCRAP_RE_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return No. {0}  has been approved. \n.
        /// </summary>
        internal static string UNUSABLE_APPROVED_BODY_1 {
            get {
                return ResourceManager.GetString("UNUSABLE_APPROVED_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This return approved by {0}. \n.
        /// </summary>
        internal static string UNUSABLE_APPROVED_BODY_2 {
            get {
                return ResourceManager.GetString("UNUSABLE_APPROVED_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return has been approved!.
        /// </summary>
        internal static string UNUSABLE_APPROVED_SUBJECT {
            get {
                return ResourceManager.GetString("UNUSABLE_APPROVED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return No. {0} has been rejected. \n.
        /// </summary>
        internal static string UNUSABLE_APPROVEREJECTED_BODY_1 {
            get {
                return ResourceManager.GetString("UNUSABLE_APPROVEREJECTED_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This return rejected by {0}. \n.
        /// </summary>
        internal static string UNUSABLE_APPROVEREJECTED_BODY_2 {
            get {
                return ResourceManager.GetString("UNUSABLE_APPROVEREJECTED_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return has been rejected!.
        /// </summary>
        internal static string UNUSABLE_APPROVEREJECTED_SUBJECT {
            get {
                return ResourceManager.GetString("UNUSABLE_APPROVEREJECTED_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New return has been created with return No.{0}. \n.
        /// </summary>
        internal static string UNUSABLE_PENDING_BODY_1 {
            get {
                return ResourceManager.GetString("UNUSABLE_PENDING_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This return is waiting for your approval. \n.
        /// </summary>
        internal static string UNUSABLE_PENDING_BODY_2 {
            get {
                return ResourceManager.GetString("UNUSABLE_PENDING_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New return has been created!.
        /// </summary>
        internal static string UNUSABLE_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("UNUSABLE_PENDING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return has been updated with return No. {0}. \n.
        /// </summary>
        internal static string UNUSABLE_RE_PENDING_BODY_1 {
            get {
                return ResourceManager.GetString("UNUSABLE_RE_PENDING_BODY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This return is waiting for your approval. \n.
        /// </summary>
        internal static string UNUSABLE_RE_PENDING_BODY_2 {
            get {
                return ResourceManager.GetString("UNUSABLE_RE_PENDING_BODY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return has been emeded!.
        /// </summary>
        internal static string UNUSABLE_RE_PENDING_SUBJECT {
            get {
                return ResourceManager.GetString("UNUSABLE_RE_PENDING_SUBJECT", resourceCulture);
            }
        }
    }
}
