//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceAircraftOverview {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAircraftOverview() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceAircraftOverview", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name of aircraft.
        /// </summary>
        internal static string LblACShortName {
            get {
                return ResourceManager.GetString("LblACShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft.
        /// </summary>
        internal static string LblAircraftOverview {
            get {
                return ResourceManager.GetString("LblAircraftOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airframe Serial No..
        /// </summary>
        internal static string LblAirframeSerialNo {
            get {
                return ResourceManager.GetString("LblAirframeSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airframe Total Cycle.
        /// </summary>
        internal static string LblAirframeTotalCycle {
            get {
                return ResourceManager.GetString("LblAirframeTotalCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airframe Total Time.
        /// </summary>
        internal static string LblAirframeTotalTime {
            get {
                return ResourceManager.GetString("LblAirframeTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Aviation Registration No.
        /// </summary>
        internal static string LblCABAuthorityRegNo {
            get {
                return ResourceManager.GetString("LblCABAuthorityRegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabin Seat Configuration.
        /// </summary>
        internal static string LblCabinSeatConfiguration {
            get {
                return ResourceManager.GetString("LblCabinSeatConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Manufacture.
        /// </summary>
        internal static string LblDateOfManufacture {
            get {
                return ResourceManager.GetString("LblDateOfManufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Location.
        /// </summary>
        internal static string LblInspectionLocation {
            get {
                return ResourceManager.GetString("LblInspectionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string LblIsActive {
            get {
                return ResourceManager.GetString("LblIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No aircraft found.
        /// </summary>
        internal static string LblNoAircraftOverviewFound {
            get {
                return ResourceManager.GetString("LblNoAircraftOverviewFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string LblRegistration {
            get {
                return ResourceManager.GetString("LblRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aricraft Model Family.
        /// </summary>
        internal static string LblScelectAricraftModelFamily {
            get {
                return ResourceManager.GetString("LblScelectAricraftModelFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total aircraft.
        /// </summary>
        internal static string LblTotalAircraftOverview {
            get {
                return ResourceManager.GetString("LblTotalAircraftOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string LblType {
            get {
                return ResourceManager.GetString("LblType", resourceCulture);
            }
        }
    }
}
