//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStockInward {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStockInward() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceStockInward", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airway Bill.
        /// </summary>
        internal static string LblAirwayBill {
            get {
                return ResourceManager.GetString("LblAirwayBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consigner.
        /// </summary>
        internal static string LblConsigner {
            get {
                return ResourceManager.GetString("LblConsigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Arrival.
        /// </summary>
        internal static string LblDateOfArrival {
            get {
                return ResourceManager.GetString("LblDateOfArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Receive.
        /// </summary>
        internal static string LblDateOfReceive {
            get {
                return ResourceManager.GetString("LblDateOfReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancy Report No..
        /// </summary>
        internal static string LblDiscripancyReportNo {
            get {
                return ResourceManager.GetString("LblDiscripancyReportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight No..
        /// </summary>
        internal static string LblFlightNo {
            get {
                return ResourceManager.GetString("LblFlightNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Description.
        /// </summary>
        internal static string LblGeneralDescription {
            get {
                return ResourceManager.GetString("LblGeneralDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Date.
        /// </summary>
        internal static string LblImportDate {
            get {
                return ResourceManager.GetString("LblImportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import No..
        /// </summary>
        internal static string LblImportNo {
            get {
                return ResourceManager.GetString("LblImportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No..
        /// </summary>
        internal static string LblInvoiceNo {
            get {
                return ResourceManager.GetString("LblInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Goods Received?.
        /// </summary>
        internal static string LblIsGoodsReceived {
            get {
                return ResourceManager.GetString("LblIsGoodsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Of Packing.
        /// </summary>
        internal static string LblModeOfPacking {
            get {
                return ResourceManager.GetString("LblModeOfPacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Of TPT.
        /// </summary>
        internal static string LblModeOfTPT {
            get {
                return ResourceManager.GetString("LblModeOfTPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Item.
        /// </summary>
        internal static string LblNoOfItem {
            get {
                return ResourceManager.GetString("LblNoOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Packing.
        /// </summary>
        internal static string LblNoOfPacking {
            get {
                return ResourceManager.GetString("LblNoOfPacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stock inward found.
        /// </summary>
        internal static string LblNoStockInwardFound {
            get {
                return ResourceManager.GetString("LblNoStockInwardFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No..
        /// </summary>
        internal static string LblOrderNo {
            get {
                return ResourceManager.GetString("LblOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Voucher No..
        /// </summary>
        internal static string LblReceiptVoucherNo {
            get {
                return ResourceManager.GetString("LblReceiptVoucherNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received By.
        /// </summary>
        internal static string LblReceivedBy {
            get {
                return ResourceManager.GetString("LblReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string LblRemarks {
            get {
                return ResourceManager.GetString("LblRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sl No..
        /// </summary>
        internal static string LblSlNo {
            get {
                return ResourceManager.GetString("LblSlNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Inward.
        /// </summary>
        internal static string LblStockInward {
            get {
                return ResourceManager.GetString("LblStockInward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Inward Details.
        /// </summary>
        internal static string LblStockInwardDetails {
            get {
                return ResourceManager.GetString("LblStockInwardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Room No..
        /// </summary>
        internal static string LblStockRoomNo {
            get {
                return ResourceManager.GetString("LblStockRoomNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Stock Inward.
        /// </summary>
        internal static string LblTotalStockInward {
            get {
                return ResourceManager.GetString("LblTotalStockInward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string LblWeight {
            get {
                return ResourceManager.GetString("LblWeight", resourceCulture);
            }
        }
    }
}
