//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceItemScrapExpireOut {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceItemScrapExpireOut() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceItemScrapExpireOut", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Item Scrap Expire Out List.
        /// </summary>
        internal static string LblAllItemScrapExpireOutList {
            get {
                return ResourceManager.GetString("LblAllItemScrapExpireOutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Item Scrap Expire Out List.
        /// </summary>
        internal static string LblApprovedItemScrapExpireOutList {
            get {
                return ResourceManager.GetString("LblApprovedItemScrapExpireOutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApprovedOn.
        /// </summary>
        internal static string LblApprovedOn {
            get {
                return ResourceManager.GetString("LblApprovedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Approved By.
        /// </summary>
        internal static string LblDecisionApprovedBy {
            get {
                return ResourceManager.GetString("LblDecisionApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Scrap Expire Out.
        /// </summary>
        internal static string LblItemScrapExpireOut {
            get {
                return ResourceManager.GetString("LblItemScrapExpireOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Scrap Expire Out Details.
        /// </summary>
        internal static string LblItemScrapExpireOutDetail {
            get {
                return ResourceManager.GetString("LblItemScrapExpireOutDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item scrap expire out found.
        /// </summary>
        internal static string LblNoItemScrapExpireOutFound {
            get {
                return ResourceManager.GetString("LblNoItemScrapExpireOutFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part No..
        /// </summary>
        internal static string LblPartNo {
            get {
                return ResourceManager.GetString("LblPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval Scrap/Expire Out List.
        /// </summary>
        internal static string LblPendingApprovalItemScrapExpireOutList {
            get {
                return ResourceManager.GetString("LblPendingApprovalItemScrapExpireOutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared By.
        /// </summary>
        internal static string LblPreparedBy {
            get {
                return ResourceManager.GetString("LblPreparedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared Item Scrap Expire Out List.
        /// </summary>
        internal static string LblPreparedItemScrapExpireOutList {
            get {
                return ResourceManager.GetString("LblPreparedItemScrapExpireOutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string LblQty {
            get {
                return ResourceManager.GetString("LblQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Date.
        /// </summary>
        internal static string LblRecordDate {
            get {
                return ResourceManager.GetString("LblRecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string LblRemark {
            get {
                return ResourceManager.GetString("LblRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap Or Expire.
        /// </summary>
        internal static string LblScrapOrExpire {
            get {
                return ResourceManager.GetString("LblScrapOrExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No.
        /// </summary>
        internal static string LblSerialNo {
            get {
                return ResourceManager.GetString("LblSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total item scrap expire out.
        /// </summary>
        internal static string LblTotalItemScrapExpireOut {
            get {
                return ResourceManager.GetString("LblTotalItemScrapExpireOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UoM.
        /// </summary>
        internal static string LblUnitOfMeasurement {
            get {
                return ResourceManager.GetString("LblUnitOfMeasurement", resourceCulture);
            }
        }
    }
}
