//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceItemReceiptVoucher {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceItemReceiptVoucher() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceItemReceiptVoucher", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airway Bill No..
        /// </summary>
        internal static string LblAirwayBillNo {
            get {
                return ResourceManager.GetString("LblAirwayBillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bincard Entry By.
        /// </summary>
        internal static string LblBincardEntryBy {
            get {
                return ResourceManager.GetString("LblBincardEntryBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bincard Entry Date.
        /// </summary>
        internal static string LblBincardEntryDate {
            get {
                return ResourceManager.GetString("LblBincardEntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified Correct By.
        /// </summary>
        internal static string LblCertifiedCorrectBy {
            get {
                return ResourceManager.GetString("LblCertifiedCorrectBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified Correct Date.
        /// </summary>
        internal static string LblCertifiedCorrectDate {
            get {
                return ResourceManager.GetString("LblCertifiedCorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified Corret SR.
        /// </summary>
        internal static string LblCertifiedCorretSR {
            get {
                return ResourceManager.GetString("LblCertifiedCorretSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deficient Damaged.
        /// </summary>
        internal static string LblDeficientDamaged {
            get {
                return ResourceManager.GetString("LblDeficientDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denomination Of Quantity.
        /// </summary>
        internal static string LblDenominationOfQuantity {
            get {
                return ResourceManager.GetString("LblDenominationOfQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DR Date.
        /// </summary>
        internal static string LblDRDate {
            get {
                return ResourceManager.GetString("LblDRDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DR No..
        /// </summary>
        internal static string LblDRNo {
            get {
                return ResourceManager.GetString("LblDRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Date.
        /// </summary>
        internal static string LblImportDate {
            get {
                return ResourceManager.GetString("LblImportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import No..
        /// </summary>
        internal static string LblImportNo {
            get {
                return ResourceManager.GetString("LblImportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent Date.
        /// </summary>
        internal static string LblIndentDate {
            get {
                return ResourceManager.GetString("LblIndentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent No..
        /// </summary>
        internal static string LblIndentNo {
            get {
                return ResourceManager.GetString("LblIndentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        internal static string LblInvoiceDate {
            get {
                return ResourceManager.GetString("LblInvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No..
        /// </summary>
        internal static string LblInvoiceNo {
            get {
                return ResourceManager.GetString("LblInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Book No..
        /// </summary>
        internal static string LblInwardBookNo {
            get {
                return ResourceManager.GetString("LblInwardBookNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InwardDate.
        /// </summary>
        internal static string LblInwardDate {
            get {
                return ResourceManager.GetString("LblInwardDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Receipt Voucher.
        /// </summary>
        internal static string LblItemReceiptVoucher {
            get {
                return ResourceManager.GetString("LblItemReceiptVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Receipt Voucher Details.
        /// </summary>
        internal static string LblItemReceiptVoucherDetail {
            get {
                return ResourceManager.GetString("LblItemReceiptVoucherDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC No..
        /// </summary>
        internal static string LblLCNo {
            get {
                return ResourceManager.GetString("LblLCNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item receipt voucher found.
        /// </summary>
        internal static string LblNoItemReceiptVoucherFound {
            get {
                return ResourceManager.GetString("LblNoItemReceiptVoucherFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part No..
        /// </summary>
        internal static string LblPartNo {
            get {
                return ResourceManager.GetString("LblPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        internal static string LblPurchaseDate {
            get {
                return ResourceManager.GetString("LblPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order No..
        /// </summary>
        internal static string LblPurchaseOrderNo {
            get {
                return ResourceManager.GetString("LblPurchaseOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Invoice.
        /// </summary>
        internal static string LblQuantityInvoice {
            get {
                return ResourceManager.GetString("LblQuantityInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Received.
        /// </summary>
        internal static string LblQuantityReceived {
            get {
                return ResourceManager.GetString("LblQuantityReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Date.
        /// </summary>
        internal static string LblReceiptDate {
            get {
                return ResourceManager.GetString("LblReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt SR No..
        /// </summary>
        internal static string LblReceiptSRNo {
            get {
                return ResourceManager.GetString("LblReceiptSRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Voucher No..
        /// </summary>
        internal static string LblReceiptVoucherNo {
            get {
                return ResourceManager.GetString("LblReceiptVoucherNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received By.
        /// </summary>
        internal static string LblReceivedBy {
            get {
                return ResourceManager.GetString("LblReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        internal static string LblReleaseDate {
            get {
                return ResourceManager.GetString("LblReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release No..
        /// </summary>
        internal static string LblReleaseNo {
            get {
                return ResourceManager.GetString("LblReleaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Outstanding.
        /// </summary>
        internal static string LblSupplyOutstanding {
            get {
                return ResourceManager.GetString("LblSupplyOutstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surplus.
        /// </summary>
        internal static string LblSurplus {
            get {
                return ResourceManager.GetString("LblSurplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total item receipt voucher.
        /// </summary>
        internal static string LblTotalItemReceiptVoucher {
            get {
                return ResourceManager.GetString("LblTotalItemReceiptVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Value.
        /// </summary>
        internal static string LblTotalValue {
            get {
                return ResourceManager.GetString("LblTotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string LblUnitPrice {
            get {
                return ResourceManager.GetString("LblUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack By.
        /// </summary>
        internal static string LblUnpackBy {
            get {
                return ResourceManager.GetString("LblUnpackBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack Date.
        /// </summary>
        internal static string LblUnpackDate {
            get {
                return ResourceManager.GetString("LblUnpackDate", resourceCulture);
            }
        }
    }
}
