//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceRack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceRack() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceRack", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string LblCode {
            get {
                return ResourceManager.GetString("LblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string LblHeight {
            get {
                return ResourceManager.GetString("LblHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rack Found.
        /// </summary>
        internal static string LblNoRackFound {
            get {
                return ResourceManager.GetString("LblNoRackFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack.
        /// </summary>
        internal static string LblRack {
            get {
                return ResourceManager.GetString("LblRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Rack Row Bin.
        /// </summary>
        internal static string LblRackRowBinCount {
            get {
                return ResourceManager.GetString("LblRackRowBinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Rack Row.
        /// </summary>
        internal static string LblRackRowCount {
            get {
                return ResourceManager.GetString("LblRackRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string LblRoom {
            get {
                return ResourceManager.GetString("LblRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Room.
        /// </summary>
        internal static string LblSelRoom {
            get {
                return ResourceManager.GetString("LblSelRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Store.
        /// </summary>
        internal static string LblSelStore {
            get {
                return ResourceManager.GetString("LblSelStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string LblStore {
            get {
                return ResourceManager.GetString("LblStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rack.
        /// </summary>
        internal static string LblTotalRack {
            get {
                return ResourceManager.GetString("LblTotalRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string LblWidth {
            get {
                return ResourceManager.GetString("LblWidth", resourceCulture);
            }
        }
    }
}
