//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceActivity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceActivity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceActivity", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        internal static string LblActivity {
            get {
                return ResourceManager.GetString("LblActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent Station.
        /// </summary>
        internal static string LblDependentActivity {
            get {
                return ResourceManager.GetString("LblDependentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Station Found..
        /// </summary>
        internal static string LblNoActivityFound {
            get {
                return ResourceManager.GetString("LblNoActivityFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dependent.
        /// </summary>
        internal static string LblNoDependent {
            get {
                return ResourceManager.GetString("LblNoDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Station in Process found.
        /// </summary>
        internal static string LblNoProcessActivityFound {
            get {
                return ResourceManager.GetString("LblNoProcessActivityFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Process Found..
        /// </summary>
        internal static string LblNoProcessFound {
            get {
                return ResourceManager.GetString("LblNoProcessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Model Family Process Station Found..
        /// </summary>
        internal static string LblNoProcessProjectActivityFound {
            get {
                return ResourceManager.GetString("LblNoProcessProjectActivityFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string LblProcess {
            get {
                return ResourceManager.GetString("LblProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Station.
        /// </summary>
        internal static string LblProcessActivity {
            get {
                return ResourceManager.GetString("LblProcessActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Family Process Station.
        /// </summary>
        internal static string LblProcessProjectActivity {
            get {
                return ResourceManager.GetString("LblProcessProjectActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string LblSequence {
            get {
                return ResourceManager.GetString("LblSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Routing.
        /// </summary>
        internal static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Station.
        /// </summary>
        internal static string LblTotalActivity {
            get {
                return ResourceManager.GetString("LblTotalActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Process Station.
        /// </summary>
        internal static string LblTotalProcessActivity {
            get {
                return ResourceManager.GetString("LblTotalProcessActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Model Family Process Station.
        /// </summary>
        internal static string LblTotalProcessProjectActivity {
            get {
                return ResourceManager.GetString("LblTotalProcessProjectActivity", resourceCulture);
            }
        }
    }
}
