//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceAircraftComponent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAircraftComponent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceAircraftComponent", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Item.
        /// </summary>
        internal static string LblAircraftComponent {
            get {
                return ResourceManager.GetString("LblAircraftComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Component Details.
        /// </summary>
        internal static string LblAircraftComponentDetails {
            get {
                return ResourceManager.GetString("LblAircraftComponentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LblAircraftComponentName {
            get {
                return ResourceManager.GetString("LblAircraftComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Component.
        /// </summary>
        internal static string LblAircraftMajorComponentId {
            get {
                return ResourceManager.GetString("LblAircraftMajorComponentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Part Number.
        /// </summary>
        internal static string LblAlternatePartNumber {
            get {
                return ResourceManager.GetString("LblAlternatePartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Type.
        /// </summary>
        internal static string LblComponentTypeId {
            get {
                return ResourceManager.GetString("LblComponentTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard (Cycle).
        /// </summary>
        internal static string LblDiscardCycle {
            get {
                return ResourceManager.GetString("LblDiscardCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard (Hour).
        /// </summary>
        internal static string LblDiscardHour {
            get {
                return ResourceManager.GetString("LblDiscardHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC Reference.
        /// </summary>
        internal static string LblIPCReferance {
            get {
                return ResourceManager.GetString("LblIPCReferance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Consumable.
        /// </summary>
        internal static string LblIsConsumable {
            get {
                return ResourceManager.GetString("LblIsConsumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Aircraft Component found.
        /// </summary>
        internal static string LblNoAircraftComponentFound {
            get {
                return ResourceManager.GetString("LblNoAircraftComponentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OH (Cycle).
        /// </summary>
        internal static string LblOHCycle {
            get {
                return ResourceManager.GetString("LblOHCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OH (Hour).
        /// </summary>
        internal static string LblOHHour {
            get {
                return ResourceManager.GetString("LblOHHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        internal static string LblPartNumber {
            get {
                return ResourceManager.GetString("LblPartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        internal static string LblReorderLevel {
            get {
                return ResourceManager.GetString("LblReorderLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string LblSerialNumber {
            get {
                return ResourceManager.GetString("LblSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since New (Cycle).
        /// </summary>
        internal static string LblSinceNewCycle {
            get {
                return ResourceManager.GetString("LblSinceNewCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since New (Hour).
        /// </summary>
        internal static string LblSinceNewHour {
            get {
                return ResourceManager.GetString("LblSinceNewHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Aircraft Component.
        /// </summary>
        internal static string LblTotalAircraftComponent {
            get {
                return ResourceManager.GetString("LblTotalAircraftComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Of Measurement.
        /// </summary>
        internal static string LblUnitOfMeasurement {
            get {
                return ResourceManager.GetString("LblUnitOfMeasurement", resourceCulture);
            }
        }
    }
}
