//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceWorkflowactionSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceWorkflowactionSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceWorkflowactionSetting", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Employee(s).
        /// </summary>
        internal static string LblAvailableEmployee {
            get {
                return ResourceManager.GetString("LblAvailableEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter in available employees.
        /// </summary>
        internal static string LblFilterInAvailableEmp {
            get {
                return ResourceManager.GetString("LblFilterInAvailableEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No approval setting found.
        /// </summary>
        internal static string LblNoWorkflowactionSettingFound {
            get {
                return ResourceManager.GetString("LblNoWorkflowactionSettingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, Select Sub Module Item!.
        /// </summary>
        internal static string LblPlsSelectUrl {
            get {
                return ResourceManager.GetString("LblPlsSelectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Employee(s).
        /// </summary>
        internal static string LblSelectedEmployee {
            get {
                return ResourceManager.GetString("LblSelectedEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total approval setting.
        /// </summary>
        internal static string LblTotalWorkflowactionSetting {
            get {
                return ResourceManager.GetString("LblTotalWorkflowactionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Setting.
        /// </summary>
        internal static string LblWorkflowactionSetting {
            get {
                return ResourceManager.GetString("LblWorkflowactionSetting", resourceCulture);
            }
        }
    }
}
