//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceUnUsableItemReturn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUnUsableItemReturn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceUnUsableItemReturn", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance Date.
        /// </summary>
        internal static string LblAcceptanceDate {
            get {
                return ResourceManager.GetString("LblAcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting Store Keeper.
        /// </summary>
        internal static string LblAcceptingStoreKeeper {
            get {
                return ResourceManager.GetString("LblAcceptingStoreKeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Regn..
        /// </summary>
        internal static string LblACRegistrationNo {
            get {
                return ResourceManager.GetString("LblACRegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Line No..
        /// </summary>
        internal static string LblCardLineNo {
            get {
                return ResourceManager.GetString("LblCardLineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentCode.
        /// </summary>
        internal static string LblDepartmentCode {
            get {
                return ResourceManager.GetString("LblDepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No unusable item return found.
        /// </summary>
        internal static string LblNoUnUsableItemReturnFound {
            get {
                return ResourceManager.GetString("LblNoUnUsableItemReturnFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part No..
        /// </summary>
        internal static string LblPartNo {
            get {
                return ResourceManager.GetString("LblPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Returned.
        /// </summary>
        internal static string LblQuantityReturned {
            get {
                return ResourceManager.GetString("LblQuantityReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release On.
        /// </summary>
        internal static string LblReleaseOn {
            get {
                return ResourceManager.GetString("LblReleaseOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Approved By.
        /// </summary>
        internal static string LblReturnApprovedBy {
            get {
                return ResourceManager.GetString("LblReturnApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Approved On.
        /// </summary>
        internal static string LblReturnApprovedOn {
            get {
                return ResourceManager.GetString("LblReturnApprovedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned On.
        /// </summary>
        internal static string LblReturnedOn {
            get {
                return ResourceManager.GetString("LblReturnedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning Officer.
        /// </summary>
        internal static string LblReturningOfficer {
            get {
                return ResourceManager.GetString("LblReturningOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Personal Date.
        /// </summary>
        internal static string LblReturnPersonalDate {
            get {
                return ResourceManager.GetString("LblReturnPersonalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Personal Staff.
        /// </summary>
        internal static string LblReturnPersonalStaff {
            get {
                return ResourceManager.GetString("LblReturnPersonalStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return SL No..
        /// </summary>
        internal static string LblReturnSLNo {
            get {
                return ResourceManager.GetString("LblReturnSLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Voucher No..
        /// </summary>
        internal static string LblReturnVoucherNo {
            get {
                return ResourceManager.GetString("LblReturnVoucherNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No..
        /// </summary>
        internal static string LblSerialNo {
            get {
                return ResourceManager.GetString("LblSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviceable Qunatity.
        /// </summary>
        internal static string LblServiceAbleQunatity {
            get {
                return ResourceManager.GetString("LblServiceAbleQunatity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Code.
        /// </summary>
        internal static string LblShopCode {
            get {
                return ResourceManager.GetString("LblShopCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Room No..
        /// </summary>
        internal static string LblStockRoomNo {
            get {
                return ResourceManager.GetString("LblStockRoomNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total unusable item return.
        /// </summary>
        internal static string LblTotalUnUsableItemReturn {
            get {
                return ResourceManager.GetString("LblTotalUnUsableItemReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Of Measurement.
        /// </summary>
        internal static string LblUnitOfMeasurement {
            get {
                return ResourceManager.GetString("LblUnitOfMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Serviceable Qunatity.
        /// </summary>
        internal static string LblUnServiceAbleQunatity {
            get {
                return ResourceManager.GetString("LblUnServiceAbleQunatity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusable Item Return.
        /// </summary>
        internal static string LblUnUsableItemReturn {
            get {
                return ResourceManager.GetString("LblUnUsableItemReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusable Item Return Details.
        /// </summary>
        internal static string LblUnUsableItemReturnDetail {
            get {
                return ResourceManager.GetString("LblUnUsableItemReturnDetail", resourceCulture);
            }
        }
    }
}
