//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcePurchaseOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePurchaseOrder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourcePurchaseOrder", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        internal static string LblApprovedBy {
            get {
                return ResourceManager.GetString("LblApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached PID Doc Name.
        /// </summary>
        internal static string LblAttachePidDoc {
            get {
                return ResourceManager.GetString("LblAttachePidDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked By.
        /// </summary>
        internal static string LblCheckBy {
            get {
                return ResourceManager.GetString("LblCheckBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked Date.
        /// </summary>
        internal static string LblCheckedOn {
            get {
                return ResourceManager.GetString("LblCheckedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative Statement.
        /// </summary>
        internal static string LblCS {
            get {
                return ResourceManager.GetString("LblCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LblDate {
            get {
                return ResourceManager.GetString("LblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demanded Department Name.
        /// </summary>
        internal static string LblDemandName {
            get {
                return ResourceManager.GetString("LblDemandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand  Quantity.
        /// </summary>
        internal static string LblDemandQuantity {
            get {
                return ResourceManager.GetString("LblDemandQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition Description.
        /// </summary>
        internal static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Overview Name.
        /// </summary>
        internal static string LblForAircraft {
            get {
                return ResourceManager.GetString("LblForAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiated By.
        /// </summary>
        internal static string LblIniatiatedBy {
            get {
                return ResourceManager.GetString("LblIniatiatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        internal static string LblInvoiceNo {
            get {
                return ResourceManager.GetString("LblInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC Reference.
        /// </summary>
        internal static string LblIPC {
            get {
                return ResourceManager.GetString("LblIPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPCOrCMMRef.
        /// </summary>
        internal static string LblIPCOrCMMRef {
            get {
                return ResourceManager.GetString("LblIPCOrCMMRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Found.
        /// </summary>
        internal static string LblNoPurchaseOrderFound {
            get {
                return ResourceManager.GetString("LblNoPurchaseOrderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Quantity.
        /// </summary>
        internal static string LblOrderQuantity {
            get {
                return ResourceManager.GetString("LblOrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        internal static string LblPart {
            get {
                return ResourceManager.GetString("LblPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        internal static string LblPO {
            get {
                return ResourceManager.GetString("LblPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present Stock.
        /// </summary>
        internal static string LblPresentStock {
            get {
                return ResourceManager.GetString("LblPresentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Date.
        /// </summary>
        internal static string LblPreviousDate {
            get {
                return ResourceManager.GetString("LblPreviousDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Price.
        /// </summary>
        internal static string LblPreviousPrice {
            get {
                return ResourceManager.GetString("LblPreviousPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Purchase Order No.
        /// </summary>
        internal static string LblPreviousPurchaseOrderNo {
            get {
                return ResourceManager.GetString("LblPreviousPurchaseOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string LblPriority {
            get {
                return ResourceManager.GetString("LblPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Date.
        /// </summary>
        internal static string LblProcurementApprovedOn {
            get {
                return ResourceManager.GetString("LblProcurementApprovedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        internal static string LblPurchaseOrder {
            get {
                return ResourceManager.GetString("LblPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Details.
        /// </summary>
        internal static string LblPurchaseOrderDetail {
            get {
                return ResourceManager.GetString("LblPurchaseOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Request.
        /// </summary>
        internal static string LblQR {
            get {
                return ResourceManager.GetString("LblQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Remark.
        /// </summary>
        internal static string LblRemarks {
            get {
                return ResourceManager.GetString("LblRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Remark.
        /// </summary>
        internal static string LblReviewRemark {
            get {
                return ResourceManager.GetString("LblReviewRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Address.
        /// </summary>
        internal static string LblShipAdd {
            get {
                return ResourceManager.GetString("LblShipAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        internal static string LblSupNme {
            get {
                return ResourceManager.GetString("LblSupNme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string LblSupplierId {
            get {
                return ResourceManager.GetString("LblSupplierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        internal static string LblSupplierName {
            get {
                return ResourceManager.GetString("LblSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Condition.
        /// </summary>
        internal static string LblTC {
            get {
                return ResourceManager.GetString("LblTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total At End.
        /// </summary>
        internal static string LblTotalAtEnd {
            get {
                return ResourceManager.GetString("LblTotalAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total Purchase Order.
        /// </summary>
        internal static string LblTotalPO {
            get {
                return ResourceManager.GetString("LblTotalPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Purchase Order.
        /// </summary>
        internal static string LblTotalPurchaseOrder {
            get {
                return ResourceManager.GetString("LblTotalPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Of Measurement DQ.
        /// </summary>
        internal static string LblUnitOfMeasurementDQ {
            get {
                return ResourceManager.GetString("LblUnitOfMeasurementDQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Of Measurement.
        /// </summary>
        internal static string LblUnitOfMeasurementOQ {
            get {
                return ResourceManager.GetString("LblUnitOfMeasurementOQ", resourceCulture);
            }
        }
    }
}
