//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGoodsReceive {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGoodsReceive() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceGoodsReceive", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consinee.
        /// </summary>
        internal static string LblConsinee {
            get {
                return ResourceManager.GetString("LblConsinee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string LblExpiryDate {
            get {
                return ResourceManager.GetString("LblExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Receive.
        /// </summary>
        internal static string LblGoodsReceive {
            get {
                return ResourceManager.GetString("LblGoodsReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Receive Details.
        /// </summary>
        internal static string LblGoodsReceiveDetails {
            get {
                return ResourceManager.GetString("LblGoodsReceiveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G. R. No..
        /// </summary>
        internal static string LblGRNo {
            get {
                return ResourceManager.GetString("LblGRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRR Date.
        /// </summary>
        internal static string LblGRRDate {
            get {
                return ResourceManager.GetString("LblGRRDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Stock Date.
        /// </summary>
        internal static string LblInwardStockDate {
            get {
                return ResourceManager.GetString("LblInwardStockDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No goods receive found.
        /// </summary>
        internal static string LblNoGoodsReceived {
            get {
                return ResourceManager.GetString("LblNoGoodsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No goods receive found.
        /// </summary>
        internal static string LblNoGoodsReceiveFound {
            get {
                return ResourceManager.GetString("LblNoGoodsReceiveFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string LblQty {
            get {
                return ResourceManager.GetString("LblQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack Life Type.
        /// </summary>
        internal static string LblRackLifeType {
            get {
                return ResourceManager.GetString("LblRackLifeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received By.
        /// </summary>
        internal static string LblReceivedBy {
            get {
                return ResourceManager.GetString("LblReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string LblRemarks {
            get {
                return ResourceManager.GetString("LblRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIB No..
        /// </summary>
        internal static string LblSIBNo {
            get {
                return ResourceManager.GetString("LblSIBNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/No..
        /// </summary>
        internal static string LblSNo {
            get {
                return ResourceManager.GetString("LblSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total goods receive.
        /// </summary>
        internal static string LblTotalGoodsReceive {
            get {
                return ResourceManager.GetString("LblTotalGoodsReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher No..
        /// </summary>
        internal static string LblVoucherNo {
            get {
                return ResourceManager.GetString("LblVoucherNo", resourceCulture);
            }
        }
    }
}
