//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFileFeedConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFileFeedConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceFileFeedConfiguration", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Table Configuration.
        /// </summary>
        internal static string LblAddNewTableConfiguration {
            get {
                return ResourceManager.GetString("LblAddNewTableConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        internal static string LblCell {
            get {
                return ResourceManager.GetString("LblCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Name.
        /// </summary>
        internal static string LblCellName {
            get {
                return ResourceManager.GetString("LblCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string LblColumn {
            get {
                return ResourceManager.GetString("LblColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string LblComment {
            get {
                return ResourceManager.GetString("LblComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Column.
        /// </summary>
        internal static string LblDbColumn {
            get {
                return ResourceManager.GetString("LblDbColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Table.
        /// </summary>
        internal static string LblDbTable {
            get {
                return ResourceManager.GetString("LblDbTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Info.
        /// </summary>
        internal static string LblDetailInfo {
            get {
                return ResourceManager.GetString("LblDetailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Configuration Table.
        /// </summary>
        internal static string LblFileConfigurationTable {
            get {
                return ResourceManager.GetString("LblFileConfigurationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extension.
        /// </summary>
        internal static string LblFileExtension {
            get {
                return ResourceManager.GetString("LblFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Feed Configuration.
        /// </summary>
        internal static string LblFileFeedConfiguration {
            get {
                return ResourceManager.GetString("LblFileFeedConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Type.
        /// </summary>
        internal static string LblFileFeedConfType {
            get {
                return ResourceManager.GetString("LblFileFeedConfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder From.
        /// </summary>
        internal static string LblFolderFrom {
            get {
                return ResourceManager.GetString("LblFolderFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder To.
        /// </summary>
        internal static string LblFolderTo {
            get {
                return ResourceManager.GetString("LblFolderTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # heading line.
        /// </summary>
        internal static string LblHeadingLineNo {
            get {
                return ResourceManager.GetString("LblHeadingLineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Unique?.
        /// </summary>
        internal static string LblIsUnique {
            get {
                return ResourceManager.GetString("LblIsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupTableName.ColumnName.
        /// </summary>
        internal static string LblLookupTableNameColumnName {
            get {
                return ResourceManager.GetString("LblLookupTableNameColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Feed Configuration found!.
        /// </summary>
        internal static string LblNoFileFeedConfigurationFound {
            get {
                return ResourceManager.GetString("LblNoFileFeedConfigurationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample File.
        /// </summary>
        internal static string LblSampleFile {
            get {
                return ResourceManager.GetString("LblSampleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        internal static string LblSheet {
            get {
                return ResourceManager.GetString("LblSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Number.
        /// </summary>
        internal static string LblSheetNumber {
            get {
                return ResourceManager.GetString("LblSheetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet #.
        /// </summary>
        internal static string LblSheetNumberHashSign {
            get {
                return ResourceManager.GetString("LblSheetNumberHashSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Row(s).
        /// </summary>
        internal static string LblSkipRows {
            get {
                return ResourceManager.GetString("LblSkipRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string LblTable {
            get {
                return ResourceManager.GetString("LblTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Cell Mapping For.
        /// </summary>
        internal static string LblTableCellMapping {
            get {
                return ResourceManager.GetString("LblTableCellMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableName.ColumnName.
        /// </summary>
        internal static string LblTableNameColumnName {
            get {
                return ResourceManager.GetString("LblTableNameColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total File Feed Configuration.
        /// </summary>
        internal static string LblTotalFileFeedConfiguration {
            get {
                return ResourceManager.GetString("LblTotalFileFeedConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Sample File.
        /// </summary>
        internal static string LblUploadSampleFile {
            get {
                return ResourceManager.GetString("LblUploadSampleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Cell Mapping Details.
        /// </summary>
        internal static string LbtTableCellMappingDetails {
            get {
                return ResourceManager.GetString("LbtTableCellMappingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension not macth with uploaded sample file.
        /// </summary>
        internal static string MgsACurrectFormatFile {
            get {
                return ResourceManager.GetString("MgsACurrectFormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} result saved from file &apos;{1}&apos;, Row: &apos;{2}&apos;, .
        /// </summary>
        internal static string MgsAITTestListSave {
            get {
                return ResourceManager.GetString("MgsAITTestListSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} result updated from file &apos;{1}&apos;, Row: &apos;{2}&apos;,.
        /// </summary>
        internal static string MgsAITTestListUpdate {
            get {
                return ResourceManager.GetString("MgsAITTestListUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose only xlsx, xls or csv type file..
        /// </summary>
        internal static string MgsChooseOnlyXlsxXlsOrCsvTypeFile {
            get {
                return ResourceManager.GetString("MgsChooseOnlyXlsxXlsOrCsvTypeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration details deleted successfully, instead system configured tables deletion..
        /// </summary>
        internal static string MgsDeleteDetailsNotSystemConfiguredTables {
            get {
                return ResourceManager.GetString("MgsDeleteDetailsNotSystemConfiguredTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Folder From&apos; information is not provided in file feed congiguration. .
        /// </summary>
        internal static string MgsFolderFromNotSet {
            get {
                return ResourceManager.GetString("MgsFolderFromNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Folder To&apos; was not provided in file feed configuration to move. .
        /// </summary>
        internal static string MgsFolderToNotSet {
            get {
                return ResourceManager.GetString("MgsFolderToNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCBASN Not Exist .
        /// </summary>
        internal static string MgsIsNotExist {
            get {
                return ResourceManager.GetString("MgsIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configureation found to save {0} result. .
        /// </summary>
        internal static string MgsNoConfigurationFound {
            get {
                return ResourceManager.GetString("MgsNoConfigurationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file found in the source folder. .
        /// </summary>
        internal static string MgsNoFileFoundInSourceFolder {
            get {
                return ResourceManager.GetString("MgsNoFileFoundInSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Process Station found for the requested URL &apos;{0}&apos;. .
        /// </summary>
        internal static string MgsNoProcessStationFoundForRequestedURL {
            get {
                return ResourceManager.GetString("MgsNoProcessStationFoundForRequestedURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source folder found for {0} files. .
        /// </summary>
        internal static string MgsNoSourceFolderFound {
            get {
                return ResourceManager.GetString("MgsNoSourceFolderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MgsNotAssociation {
            get {
                return ResourceManager.GetString("MgsNotAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify from local/network drive.
        /// </summary>
        internal static string MgsSpecifyFromLocalOrNetworkDrive {
            get {
                return ResourceManager.GetString("MgsSpecifyFromLocalOrNetworkDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WD Model No. does not match, .
        /// </summary>
        internal static string MgsWDModelNotMatch {
            get {
                return ResourceManager.GetString("MgsWDModelNotMatch", resourceCulture);
            }
        }
    }
}
