//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceMenu", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Component.
        /// </summary>
        internal static string AircraftComponent {
            get {
                return ResourceManager.GetString("AircraftComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Component.
        /// </summary>
        internal static string AircraftMajorComponent {
            get {
                return ResourceManager.GetString("AircraftMajorComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Model Family.
        /// </summary>
        internal static string AircraftModelFamily {
            get {
                return ResourceManager.GetString("AircraftModelFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Overview.
        /// </summary>
        internal static string AircraftOverview {
            get {
                return ResourceManager.GetString("AircraftOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparativeStatementApprovedList.
        /// </summary>
        internal static string ComparativeStatementApprovedList {
            get {
                return ResourceManager.GetString("ComparativeStatementApprovedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparativeStatementList.
        /// </summary>
        internal static string ComparativeStatementList {
            get {
                return ResourceManager.GetString("ComparativeStatementList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparativeStatementPendingList.
        /// </summary>
        internal static string ComparativeStatementPendingList {
            get {
                return ResourceManager.GetString("ComparativeStatementPendingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparativeStatementReviewedList.
        /// </summary>
        internal static string ComparativeStatementReviewedList {
            get {
                return ResourceManager.GetString("ComparativeStatementReviewedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        internal static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Group.
        /// </summary>
        internal static string ComponentGroup {
            get {
                return ResourceManager.GetString("ComponentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Type.
        /// </summary>
        internal static string ComponentType {
            get {
                return ResourceManager.GetString("ComponentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite Component.
        /// </summary>
        internal static string CompositeComponent {
            get {
                return ResourceManager.GetString("CompositeComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand.
        /// </summary>
        internal static string Demand {
            get {
                return ResourceManager.GetString("Demand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment History.
        /// </summary>
        internal static string EmploymentHistory {
            get {
                return ResourceManager.GetString("EmploymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Department.
        /// </summary>
        internal static string ExternalDepartment {
            get {
                return ResourceManager.GetString("ExternalDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Operation.
        /// </summary>
        internal static string FlightOperation {
            get {
                return ResourceManager.GetString("FlightOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoodRecievedInspaction.
        /// </summary>
        internal static string GoodRecievedInspaction {
            get {
                return ResourceManager.GetString("GoodRecievedInspaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Receive.
        /// </summary>
        internal static string GoodsReceive {
            get {
                return ResourceManager.GetString("GoodsReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Receive List.
        /// </summary>
        internal static string GoodsReceiveList {
            get {
                return ResourceManager.GetString("GoodsReceiveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        internal static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Opening.
        /// </summary>
        internal static string InventoryOpening {
            get {
                return ResourceManager.GetString("InventoryOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Demand.
        /// </summary>
        internal static string ItemDemand {
            get {
                return ResourceManager.GetString("ItemDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Issue.
        /// </summary>
        internal static string ItemIssue {
            get {
                return ResourceManager.GetString("ItemIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Issue List.
        /// </summary>
        internal static string ItemIssueList {
            get {
                return ResourceManager.GetString("ItemIssueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Receipt Voucher.
        /// </summary>
        internal static string ItemReceiptVoucher {
            get {
                return ResourceManager.GetString("ItemReceiptVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Scrap Expire Out.
        /// </summary>
        internal static string ItemScrapExpireOut {
            get {
                return ResourceManager.GetString("ItemScrapExpireOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Setting.
        /// </summary>
        internal static string NotificationSetting {
            get {
                return ResourceManager.GetString("NotificationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening.
        /// </summary>
        internal static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Accept Unusable Item Return List.
        /// </summary>
        internal static string PendingAcceptUnUsableItemReturn {
            get {
                return ResourceManager.GetString("PendingAcceptUnUsableItemReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval Unusable Item Return List.
        /// </summary>
        internal static string PendingApprovalUnUsableItemReturn {
            get {
                return ResourceManager.GetString("PendingApprovalUnUsableItemReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        internal static string Planning {
            get {
                return ResourceManager.GetString("Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement.
        /// </summary>
        internal static string Procurement {
            get {
                return ResourceManager.GetString("Procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcurementQuoteRequestItem.
        /// </summary>
        internal static string ProcurementQuoteRequestItem {
            get {
                return ResourceManager.GetString("ProcurementQuoteRequestItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Requisition.
        /// </summary>
        internal static string ProcurementRequisition {
            get {
                return ResourceManager.GetString("ProcurementRequisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Requisition Approved List.
        /// </summary>
        internal static string ProcurementRequisitionApprovedList {
            get {
                return ResourceManager.GetString("ProcurementRequisitionApprovedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Requisition List.
        /// </summary>
        internal static string ProcurementRequisitionList {
            get {
                return ResourceManager.GetString("ProcurementRequisitionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Requisition Pending List.
        /// </summary>
        internal static string ProcurementRequisitionPendingList {
            get {
                return ResourceManager.GetString("ProcurementRequisitionPendingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Requisition Reviewed List.
        /// </summary>
        internal static string ProcurementRequisitionReviewedList {
            get {
                return ResourceManager.GetString("ProcurementRequisitionReviewedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuoteCollection.
        /// </summary>
        internal static string QuoteCollection {
            get {
                return ResourceManager.GetString("QuoteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuoteCollectionList.
        /// </summary>
        internal static string QuoteCollectionList {
            get {
                return ResourceManager.GetString("QuoteCollectionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack.
        /// </summary>
        internal static string Rack {
            get {
                return ResourceManager.GetString("Rack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack Row.
        /// </summary>
        internal static string RackRow {
            get {
                return ResourceManager.GetString("RackRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rack Row Bin.
        /// </summary>
        internal static string RackRowBin {
            get {
                return ResourceManager.GetString("RackRowBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Voucher.
        /// </summary>
        internal static string RecieptVoucher {
            get {
                return ResourceManager.GetString("RecieptVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecievedGoodInspectionEdit.
        /// </summary>
        internal static string RecievedGoodInspectionEdit {
            get {
                return ResourceManager.GetString("RecievedGoodInspectionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Configuration.
        /// </summary>
        internal static string ReportConfiguration {
            get {
                return ResourceManager.GetString("ReportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition.
        /// </summary>
        internal static string Requisition {
            get {
                return ResourceManager.GetString("Requisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Setting.
        /// </summary>
        internal static string ReviewSetting {
            get {
                return ResourceManager.GetString("ReviewSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Sub Module item.
        /// </summary>
        internal static string RoleSubModuleitem {
            get {
                return ResourceManager.GetString("RoleSubModuleitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap.
        /// </summary>
        internal static string Scrap {
            get {
                return ResourceManager.GetString("Scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Opening List.
        /// </summary>
        internal static string ShowAllInventoryOpeningList {
            get {
                return ResourceManager.GetString("ShowAllInventoryOpeningList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap/Expire Out List.
        /// </summary>
        internal static string ShowAllItemScrapExpireOutList {
            get {
                return ResourceManager.GetString("ShowAllItemScrapExpireOutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Issue List.
        /// </summary>
        internal static string ShowApprovedIssueList {
            get {
                return ResourceManager.GetString("ShowApprovedIssueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Internal Demand List.
        /// </summary>
        internal static string ShowApprovedItemDemandList {
            get {
                return ResourceManager.GetString("ShowApprovedItemDemandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Issue List.
        /// </summary>
        internal static string ShowIssuedIssueList {
            get {
                return ResourceManager.GetString("ShowIssuedIssueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Issue List.
        /// </summary>
        internal static string ShowPendingIssueList {
            get {
                return ResourceManager.GetString("ShowPendingIssueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared Scrap Expire Out List.
        /// </summary>
        internal static string ShowPendingItemScrapExpireOutList {
            get {
                return ResourceManager.GetString("ShowPendingItemScrapExpireOutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Inventory Opening List.
        /// </summary>
        internal static string ShowPrendingInventoryOpeningList {
            get {
                return ResourceManager.GetString("ShowPrendingInventoryOpeningList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared Internal Demand List.
        /// </summary>
        internal static string ShowPreparedItemDemandList {
            get {
                return ResourceManager.GetString("ShowPreparedItemDemandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Admin.
        /// </summary>
        internal static string SiteAdmin {
            get {
                return ResourceManager.GetString("SiteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Inward.
        /// </summary>
        internal static string StockInward {
            get {
                return ResourceManager.GetString("StockInward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Inward List.
        /// </summary>
        internal static string StockInwardList {
            get {
                return ResourceManager.GetString("StockInwardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Module.
        /// </summary>
        internal static string SubModule {
            get {
                return ResourceManager.GetString("SubModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Module Item.
        /// </summary>
        internal static string SubModuleItem {
            get {
                return ResourceManager.GetString("SubModuleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Of Measurement.
        /// </summary>
        internal static string UnitOfMeasurement {
            get {
                return ResourceManager.GetString("UnitOfMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusable Item Return.
        /// </summary>
        internal static string UnusableItem {
            get {
                return ResourceManager.GetString("UnusableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusable Item Return.
        /// </summary>
        internal static string UnUsableItemReturn {
            get {
                return ResourceManager.GetString("UnUsableItemReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusable Item Return List.
        /// </summary>
        internal static string UnUsableItemReturnList {
            get {
                return ResourceManager.GetString("UnUsableItemReturnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusable Return.
        /// </summary>
        internal static string UnusableReturn {
            get {
                return ResourceManager.GetString("UnusableReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Action Setting.
        /// </summary>
        internal static string WorkflowactionSetting {
            get {
                return ResourceManager.GetString("WorkflowactionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        internal static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
    }
}
